variables:
    PLUGIN_NAME : 'fullJournalTransfer'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_3_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'

plugin_unit_tests_ojs:
  before_script:
    # Metrics import tests use an isolated SQLite database in memory.
    - apt-get update
    - apt-get install -y --no-install-recommends "php${PHP_VERSION}-sqlite3"
