variables:
    PLUGIN_NAME : 'fullJournalTransfer'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_4_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'
