<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:pkp="http://pkp.sfu.ca"
    targetNamespace="http://pkp.sfu.ca"
    elementFormDefault="qualified">

    <simpleType name="locale_code">
        <restriction base="string">
            <pattern value="[a-z]{2}(_[A-Z]{2})?" />
        </restriction>
    </simpleType>

    <element name="journal">
        <complexType>
            <sequence>
                <element name="locales" type="pkp:locales" />
                <element name="submission_checklist" type="pkp:submission_checklist" minOccurs="0" />
                <element name="context_settings" type="pkp:context_settings" />
                <element name="theme" type="pkp:theme" minOccurs="0" />
                <element name="users" type="pkp:open_data" minOccurs="0" />
                <element name="reference_data" type="pkp:open_data" minOccurs="0" />
                <element name="native_data" type="pkp:native_data" minOccurs="0" />
                <element name="workflow_history" type="pkp:workflow_history" minOccurs="0" />
                <element name="metrics" type="pkp:metrics" minOccurs="0" />
            </sequence>
            <attribute name="primary_locale" type="pkp:locale_code" use="required" />
            <attribute name="url_path" type="string" use="required" />
            <attribute name="sequence" type="decimal" use="required" />
            <attribute name="source_enabled" type="boolean" use="required" />
        </complexType>
    </element>

    <complexType name="locales">
        <sequence>
            <element name="locale" minOccurs="1" maxOccurs="unbounded">
                <complexType>
                    <attribute name="code" type="pkp:locale_code" use="required" />
                    <attribute name="enabled_for_forms" type="boolean" use="required" />
                    <attribute name="form_order" type="positiveInteger" use="optional" />
                    <attribute name="enabled_for_submissions" type="boolean" use="required" />
                    <attribute name="submission_order" type="positiveInteger" use="optional" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="context_settings">
        <sequence>
            <element name="setting" minOccurs="3" maxOccurs="unbounded">
                <complexType mixed="true">
                    <attribute name="name" type="string" use="required" />
                    <attribute name="type" use="required">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="string" />
                                <enumeration value="integer" />
                                <enumeration value="boolean" />
                            </restriction>
                        </simpleType>
                    </attribute>
                    <attribute name="locale" type="pkp:locale_code" use="optional" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="submission_checklist">
        <sequence>
            <element name="content" minOccurs="1" maxOccurs="unbounded">
                <complexType mixed="true">
                    <attribute name="locale" type="pkp:locale_code" use="required" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="theme">
        <sequence>
            <element name="option" minOccurs="0" maxOccurs="unbounded">
                <complexType mixed="true">
                    <attribute name="name" type="pkp:theme_option_name" use="required" />
                </complexType>
            </element>
        </sequence>
        <attribute name="plugin_path" type="pkp:plugin_identifier" use="required" />
        <attribute name="plugin_name" type="pkp:plugin_identifier" use="required" />
    </complexType>

    <simpleType name="plugin_identifier">
        <restriction base="string">
            <pattern value="[a-zA-Z0-9]+([-_][a-zA-Z0-9]+)*" />
        </restriction>
    </simpleType>

    <simpleType name="theme_option_name">
        <restriction base="string">
            <pattern value="[a-zA-Z0-9][a-zA-Z0-9_.-]*" />
        </restriction>
    </simpleType>

    <complexType name="native_data">
        <sequence>
            <element name="issue_orders" type="pkp:issue_orders" />
            <element name="issues" type="pkp:open_data" />
            <element name="articles" type="pkp:open_data" />
        </sequence>
    </complexType>

    <complexType name="issue_orders">
        <sequence>
            <element name="issue_order" type="pkp:issue_order" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="issue_order">
        <attribute name="issue_ref" type="string" use="required" />
        <attribute name="position" type="positiveInteger" use="required" />
    </complexType>

    <complexType name="open_data">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="workflow_history">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="metrics">
        <sequence>
            <element name="context_metrics" type="pkp:context_metrics" />
            <element name="submission_metrics" type="pkp:submission_metrics" />
            <element name="issue_metrics" type="pkp:issue_metrics" />
            <element name="geo_metrics" type="pkp:geo_metrics" />
            <element name="counter_metrics" type="pkp:counter_metrics" />
            <element name="institution_metrics" type="pkp:institution_metrics" />
        </sequence>
    </complexType>

    <simpleType name="load_id">
        <restriction base="string">
            <minLength value="1" />
            <maxLength value="50" />
        </restriction>
    </simpleType>

    <simpleType name="metric_granularity">
        <restriction base="string">
            <enumeration value="daily" />
            <enumeration value="monthly" />
        </restriction>
    </simpleType>

    <simpleType name="country_code">
        <restriction base="string">
            <pattern value="([A-Z]{2})?" />
        </restriction>
    </simpleType>

    <complexType name="context_metrics">
        <sequence>
            <element name="context_metric" type="pkp:context_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="context_metric">
        <attribute name="load_id" type="pkp:load_id" use="required" />
        <attribute name="date" type="date" use="required" />
        <attribute name="metric" type="nonNegativeInteger" use="required" />
    </complexType>

    <complexType name="submission_metrics">
        <sequence>
            <element name="submission_metric" type="pkp:submission_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="submission_metric">
        <attribute name="load_id" type="pkp:load_id" use="required" />
        <attribute name="submission_ref" type="string" use="required" />
        <attribute name="representation_ref" type="string" use="optional" />
        <attribute name="submission_file_ref" type="string" use="optional" />
        <attribute name="file_type" type="nonNegativeInteger" use="optional" />
        <attribute name="assoc_type" type="nonNegativeInteger" use="required" />
        <attribute name="date" type="date" use="required" />
        <attribute name="metric" type="nonNegativeInteger" use="required" />
    </complexType>

    <complexType name="issue_metrics">
        <sequence>
            <element name="issue_metric" type="pkp:issue_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="issue_metric">
        <attribute name="load_id" type="pkp:load_id" use="required" />
        <attribute name="issue_ref" type="string" use="required" />
        <attribute name="issue_galley_ref" type="string" use="optional" />
        <attribute name="date" type="date" use="required" />
        <attribute name="metric" type="nonNegativeInteger" use="required" />
    </complexType>

    <complexType name="geo_metrics">
        <sequence>
            <element name="geo_metric" type="pkp:geo_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="geo_metric">
        <attribute name="granularity" type="pkp:metric_granularity" use="required" />
        <attribute name="load_id" type="pkp:load_id" use="optional" />
        <attribute name="date" type="date" use="optional" />
        <attribute name="month" type="positiveInteger" use="optional" />
        <attribute name="submission_ref" type="string" use="required" />
        <attribute name="country" type="pkp:country_code" use="required" />
        <attribute name="region" use="required">
            <simpleType><restriction base="string"><maxLength value="3" /></restriction></simpleType>
        </attribute>
        <attribute name="city" use="required">
            <simpleType><restriction base="string"><maxLength value="255" /></restriction></simpleType>
        </attribute>
        <attribute name="metric" type="nonNegativeInteger" use="required" />
        <attribute name="metric_unique" type="nonNegativeInteger" use="required" />
    </complexType>

    <attributeGroup name="counter_values">
        <attribute name="metric_investigations" type="nonNegativeInteger" use="required" />
        <attribute name="metric_investigations_unique" type="nonNegativeInteger" use="required" />
        <attribute name="metric_requests" type="nonNegativeInteger" use="required" />
        <attribute name="metric_requests_unique" type="nonNegativeInteger" use="required" />
    </attributeGroup>

    <complexType name="counter_metrics">
        <sequence>
            <element name="counter_metric" type="pkp:counter_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="counter_metric">
        <attribute name="granularity" type="pkp:metric_granularity" use="required" />
        <attribute name="load_id" type="pkp:load_id" use="optional" />
        <attribute name="date" type="date" use="optional" />
        <attribute name="month" type="positiveInteger" use="optional" />
        <attribute name="submission_ref" type="string" use="required" />
        <attributeGroup ref="pkp:counter_values" />
    </complexType>

    <complexType name="institution_metrics">
        <sequence>
            <element name="institution_metric" type="pkp:institution_metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="institution_metric">
        <attribute name="granularity" type="pkp:metric_granularity" use="required" />
        <attribute name="load_id" type="pkp:load_id" use="optional" />
        <attribute name="date" type="date" use="optional" />
        <attribute name="month" type="positiveInteger" use="optional" />
        <attribute name="submission_ref" type="string" use="required" />
        <attribute name="source_institution_ref" type="string" use="required" />
        <attribute name="institution_ror" type="anyURI" use="optional" />
        <attributeGroup ref="pkp:counter_values" />
    </complexType>
</schema>
