<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:pkp="http://pkp.sfu.ca"
    targetNamespace="http://pkp.sfu.ca"
    elementFormDefault="qualified">

    <simpleType name="locale_code">
        <restriction base="string">
            <pattern value="[a-z]{2}(_[A-Z]{2})?" />
        </restriction>
    </simpleType>

    <element name="journal">
        <complexType>
            <sequence>
                <element name="locales" type="pkp:locales" />
                <element name="submission_checklist" type="pkp:submission_checklist" minOccurs="0" />
                <element name="context_settings" type="pkp:context_settings" />
                <element name="users" type="pkp:open_data" minOccurs="0" />
                <element name="reference_data" type="pkp:open_data" minOccurs="0" />
                <element name="native_data" type="pkp:native_data" minOccurs="0" />
                <element name="workflow_history" type="pkp:workflow_history" minOccurs="0" />
                <element name="metrics" type="pkp:metrics" minOccurs="0" />
            </sequence>
            <attribute name="primary_locale" type="pkp:locale_code" use="required" />
            <attribute name="url_path" type="string" use="required" />
            <attribute name="sequence" type="decimal" use="required" />
            <attribute name="source_enabled" type="boolean" use="required" />
        </complexType>
    </element>

    <complexType name="locales">
        <sequence>
            <element name="locale" minOccurs="1" maxOccurs="unbounded">
                <complexType>
                    <attribute name="code" type="pkp:locale_code" use="required" />
                    <attribute name="enabled_for_forms" type="boolean" use="required" />
                    <attribute name="form_order" type="positiveInteger" use="optional" />
                    <attribute name="enabled_for_submissions" type="boolean" use="required" />
                    <attribute name="submission_order" type="positiveInteger" use="optional" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="context_settings">
        <sequence>
            <element name="setting" minOccurs="3" maxOccurs="unbounded">
                <complexType mixed="true">
                    <attribute name="name" type="string" use="required" />
                    <attribute name="type" use="required">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="string" />
                                <enumeration value="integer" />
                                <enumeration value="boolean" />
                            </restriction>
                        </simpleType>
                    </attribute>
                    <attribute name="locale" type="pkp:locale_code" use="optional" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="submission_checklist">
        <sequence>
            <element name="content" minOccurs="1" maxOccurs="unbounded">
                <complexType mixed="true">
                    <attribute name="locale" type="pkp:locale_code" use="required" />
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="native_data">
        <sequence>
            <element name="issues" type="pkp:issue_records" />
            <element name="submissions" type="pkp:submission_records" />
        </sequence>
        <attribute name="current_issue_ref" type="string" use="optional" />
    </complexType>

    <complexType name="issue_records">
        <sequence>
            <element name="issue_record" type="pkp:issue_record" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="issue_record">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="1" maxOccurs="1" />
        </sequence>
        <attribute name="source_ref" type="string" use="required" />
        <attribute name="custom_order" type="positiveInteger" use="optional" />
    </complexType>

    <complexType name="submission_records">
        <sequence>
            <element name="submission_record" type="pkp:submission_record" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="submission_record">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="1" maxOccurs="1" />
        </sequence>
        <attribute name="source_ref" type="string" use="required" />
    </complexType>

    <complexType name="open_data">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="workflow_history">
        <sequence>
            <any namespace="http://pkp.sfu.ca" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="metrics">
        <sequence>
            <element name="metric" type="pkp:metric" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="metric">
        <sequence>
            <element name="dimension" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="name" type="string" use="required" />
                    <attribute name="value" type="string" use="required" />
                </complexType>
            </element>
        </sequence>
        <attribute name="family" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="context" />
                    <enumeration value="submission" />
                    <enumeration value="issue" />
                    <enumeration value="counter" />
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="value" type="nonNegativeInteger" use="required" />
        <attribute name="date" type="date" use="optional" />
    </complexType>
</schema>
